Name: Param
Type: FolderType
Children:
- Name: Param_Item
  Id: g=5d73b92abc11c3eab3074b0469248bba
  Supertype: BaseObjectType
  Children:
  - Name: Val
    Type: BaseDataVariableType
    DataType: Int32
    Children:
    - Name: DynamicLink
      Type: DynamicLink
      DataType: NodePath
      Children:
      - Name: Mode
        Type: BaseVariableType
        DataType: DynamicLinkMode
        ModellingRule: Optional
        Value: 2
      - Name: DynamicLinkFormatter
        Type: StringFormatter
        Children:
        - Name: Format
          Type: BaseDataVariableType
          DataType: LocalizedText
          ReferenceType: HasParameter
          ModellingRule: Optional
          Value: {"LocaleId":"it-IT","Text":"/Objects/Cobem_MRM_5/CommDrivers/OMRONFinsDriver/PLC/Tags/Param[{0}]"}
        - Name: ns=5;Source0
          Type: BaseDataVariableType
          DataType: BaseDataType
          ReferenceType: HasSource
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../Number@Value"
  - Name: Number
    Type: BaseDataVariableType
    DataType: Int32
    Children:
    - Name: ExpressionEvaluator1
      Type: ExpressionEvaluator
      Children:
      - Name: Expression
        Type: BaseDataVariableType
        DataType: String
        ReferenceType: HasParameter
        ModellingRule: Optional
        Value: "right_of( {0} , \"Param_Item\" )"
      - Name: ns=5;Source0
        Type: BaseDataVariableType
        DataType: BaseDataType
        ReferenceType: HasSource
        Children:
        - Name: DynamicLink
          Type: DynamicLink
          DataType: NodePath
          Value: "../../..@BrowseName"
  - Name: Description
    Type: BaseDataVariableType
    DataType: String
    Value: "0"
  - Name: Group
    Type: BaseDataVariableType
    DataType: String
    Value: "0"
  - Name: MeasureUnit
    Type: BaseDataVariableType
    DataType: String
